package com.springboot.xp.dao.mysql.model;

import java.util.Date;

public class AdminAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EMP_ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EMP_NAME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EMP_EMAIL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String empEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EMP_PWD
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String empPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EMP_PHONE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String empPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EMP_MOBILE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String empMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EMP_EXT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String empExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.ACCOUNT_TYPE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.IS_LIVE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String isLive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.CREATOR
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.CREATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date createDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.UPDATER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.UPDATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date updateDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.AM_PAY_MONEY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Long amPayMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.AM_ENTRY_CONFIRM_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Long amEntryConfirmNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.PAYMENTS_AMOUNT_COUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Long paymentsAmountCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.PAYMENTS_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Long paymentsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.JOB_DYNAMIC_INFORMATION_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date jobDynamicInformationReadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.CANDIDATE_DYNAMIC_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date candidateDynamicReadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.JOB_CONMUNICATION_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date jobConmunicationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.URL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.PREV_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date prevLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.NOW_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date nowLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EMP_WECHAT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String empWechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EMP_QQ
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String empQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EMP_LEVEL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Integer empLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.ROLE_ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.DUTIES
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String duties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.ROLE_SUBSECTION
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Long roleSubsection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.STATUS
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.POSITION_RANK
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String positionRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.SCORE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.FROZEN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date frozenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.EHR_STAFF_ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Long ehrStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN_ACCOUNT.JOB_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String jobNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EMP_ID
     *
     * @return the value of T_ADMIN_ACCOUNT.EMP_ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EMP_ID
     *
     * @param empId the value for T_ADMIN_ACCOUNT.EMP_ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EMP_NAME
     *
     * @return the value of T_ADMIN_ACCOUNT.EMP_NAME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EMP_NAME
     *
     * @param empName the value for T_ADMIN_ACCOUNT.EMP_NAME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EMP_EMAIL
     *
     * @return the value of T_ADMIN_ACCOUNT.EMP_EMAIL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EMP_EMAIL
     *
     * @param empEmail the value for T_ADMIN_ACCOUNT.EMP_EMAIL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EMP_PWD
     *
     * @return the value of T_ADMIN_ACCOUNT.EMP_PWD
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getEmpPwd() {
        return empPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EMP_PWD
     *
     * @param empPwd the value for T_ADMIN_ACCOUNT.EMP_PWD
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEmpPwd(String empPwd) {
        this.empPwd = empPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EMP_PHONE
     *
     * @return the value of T_ADMIN_ACCOUNT.EMP_PHONE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getEmpPhone() {
        return empPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EMP_PHONE
     *
     * @param empPhone the value for T_ADMIN_ACCOUNT.EMP_PHONE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEmpPhone(String empPhone) {
        this.empPhone = empPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EMP_MOBILE
     *
     * @return the value of T_ADMIN_ACCOUNT.EMP_MOBILE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getEmpMobile() {
        return empMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EMP_MOBILE
     *
     * @param empMobile the value for T_ADMIN_ACCOUNT.EMP_MOBILE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEmpMobile(String empMobile) {
        this.empMobile = empMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EMP_EXT
     *
     * @return the value of T_ADMIN_ACCOUNT.EMP_EXT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getEmpExt() {
        return empExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EMP_EXT
     *
     * @param empExt the value for T_ADMIN_ACCOUNT.EMP_EXT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEmpExt(String empExt) {
        this.empExt = empExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.ACCOUNT_TYPE
     *
     * @return the value of T_ADMIN_ACCOUNT.ACCOUNT_TYPE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.ACCOUNT_TYPE
     *
     * @param accountType the value for T_ADMIN_ACCOUNT.ACCOUNT_TYPE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.IS_LIVE
     *
     * @return the value of T_ADMIN_ACCOUNT.IS_LIVE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getIsLive() {
        return isLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.IS_LIVE
     *
     * @param isLive the value for T_ADMIN_ACCOUNT.IS_LIVE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setIsLive(String isLive) {
        this.isLive = isLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.CREATOR
     *
     * @return the value of T_ADMIN_ACCOUNT.CREATOR
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.CREATOR
     *
     * @param creator the value for T_ADMIN_ACCOUNT.CREATOR
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.CREATE_DTTM
     *
     * @return the value of T_ADMIN_ACCOUNT.CREATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getCreateDttm() {
        return createDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.CREATE_DTTM
     *
     * @param createDttm the value for T_ADMIN_ACCOUNT.CREATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.UPDATER
     *
     * @return the value of T_ADMIN_ACCOUNT.UPDATER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.UPDATER
     *
     * @param updater the value for T_ADMIN_ACCOUNT.UPDATER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.UPDATE_DTTM
     *
     * @return the value of T_ADMIN_ACCOUNT.UPDATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getUpdateDttm() {
        return updateDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.UPDATE_DTTM
     *
     * @param updateDttm the value for T_ADMIN_ACCOUNT.UPDATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.AM_PAY_MONEY
     *
     * @return the value of T_ADMIN_ACCOUNT.AM_PAY_MONEY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Long getAmPayMoney() {
        return amPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.AM_PAY_MONEY
     *
     * @param amPayMoney the value for T_ADMIN_ACCOUNT.AM_PAY_MONEY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setAmPayMoney(Long amPayMoney) {
        this.amPayMoney = amPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.AM_ENTRY_CONFIRM_NUM
     *
     * @return the value of T_ADMIN_ACCOUNT.AM_ENTRY_CONFIRM_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Long getAmEntryConfirmNum() {
        return amEntryConfirmNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.AM_ENTRY_CONFIRM_NUM
     *
     * @param amEntryConfirmNum the value for T_ADMIN_ACCOUNT.AM_ENTRY_CONFIRM_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setAmEntryConfirmNum(Long amEntryConfirmNum) {
        this.amEntryConfirmNum = amEntryConfirmNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.PAYMENTS_AMOUNT_COUNT
     *
     * @return the value of T_ADMIN_ACCOUNT.PAYMENTS_AMOUNT_COUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Long getPaymentsAmountCount() {
        return paymentsAmountCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.PAYMENTS_AMOUNT_COUNT
     *
     * @param paymentsAmountCount the value for T_ADMIN_ACCOUNT.PAYMENTS_AMOUNT_COUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setPaymentsAmountCount(Long paymentsAmountCount) {
        this.paymentsAmountCount = paymentsAmountCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.PAYMENTS_NUM
     *
     * @return the value of T_ADMIN_ACCOUNT.PAYMENTS_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Long getPaymentsNum() {
        return paymentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.PAYMENTS_NUM
     *
     * @param paymentsNum the value for T_ADMIN_ACCOUNT.PAYMENTS_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setPaymentsNum(Long paymentsNum) {
        this.paymentsNum = paymentsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.JOB_DYNAMIC_INFORMATION_READTIME
     *
     * @return the value of T_ADMIN_ACCOUNT.JOB_DYNAMIC_INFORMATION_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getJobDynamicInformationReadtime() {
        return jobDynamicInformationReadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.JOB_DYNAMIC_INFORMATION_READTIME
     *
     * @param jobDynamicInformationReadtime the value for T_ADMIN_ACCOUNT.JOB_DYNAMIC_INFORMATION_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setJobDynamicInformationReadtime(Date jobDynamicInformationReadtime) {
        this.jobDynamicInformationReadtime = jobDynamicInformationReadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.CANDIDATE_DYNAMIC_READTIME
     *
     * @return the value of T_ADMIN_ACCOUNT.CANDIDATE_DYNAMIC_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getCandidateDynamicReadtime() {
        return candidateDynamicReadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.CANDIDATE_DYNAMIC_READTIME
     *
     * @param candidateDynamicReadtime the value for T_ADMIN_ACCOUNT.CANDIDATE_DYNAMIC_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setCandidateDynamicReadtime(Date candidateDynamicReadtime) {
        this.candidateDynamicReadtime = candidateDynamicReadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.JOB_CONMUNICATION_TIME
     *
     * @return the value of T_ADMIN_ACCOUNT.JOB_CONMUNICATION_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getJobConmunicationTime() {
        return jobConmunicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.JOB_CONMUNICATION_TIME
     *
     * @param jobConmunicationTime the value for T_ADMIN_ACCOUNT.JOB_CONMUNICATION_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setJobConmunicationTime(Date jobConmunicationTime) {
        this.jobConmunicationTime = jobConmunicationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.URL
     *
     * @return the value of T_ADMIN_ACCOUNT.URL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.URL
     *
     * @param url the value for T_ADMIN_ACCOUNT.URL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.PREV_LOGIN_TIME
     *
     * @return the value of T_ADMIN_ACCOUNT.PREV_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getPrevLoginTime() {
        return prevLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.PREV_LOGIN_TIME
     *
     * @param prevLoginTime the value for T_ADMIN_ACCOUNT.PREV_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setPrevLoginTime(Date prevLoginTime) {
        this.prevLoginTime = prevLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.NOW_LOGIN_TIME
     *
     * @return the value of T_ADMIN_ACCOUNT.NOW_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getNowLoginTime() {
        return nowLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.NOW_LOGIN_TIME
     *
     * @param nowLoginTime the value for T_ADMIN_ACCOUNT.NOW_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setNowLoginTime(Date nowLoginTime) {
        this.nowLoginTime = nowLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EMP_WECHAT
     *
     * @return the value of T_ADMIN_ACCOUNT.EMP_WECHAT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getEmpWechat() {
        return empWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EMP_WECHAT
     *
     * @param empWechat the value for T_ADMIN_ACCOUNT.EMP_WECHAT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEmpWechat(String empWechat) {
        this.empWechat = empWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EMP_QQ
     *
     * @return the value of T_ADMIN_ACCOUNT.EMP_QQ
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getEmpQq() {
        return empQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EMP_QQ
     *
     * @param empQq the value for T_ADMIN_ACCOUNT.EMP_QQ
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEmpQq(String empQq) {
        this.empQq = empQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EMP_LEVEL
     *
     * @return the value of T_ADMIN_ACCOUNT.EMP_LEVEL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Integer getEmpLevel() {
        return empLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EMP_LEVEL
     *
     * @param empLevel the value for T_ADMIN_ACCOUNT.EMP_LEVEL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEmpLevel(Integer empLevel) {
        this.empLevel = empLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.ROLE_ID
     *
     * @return the value of T_ADMIN_ACCOUNT.ROLE_ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.ROLE_ID
     *
     * @param roleId the value for T_ADMIN_ACCOUNT.ROLE_ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.DUTIES
     *
     * @return the value of T_ADMIN_ACCOUNT.DUTIES
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getDuties() {
        return duties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.DUTIES
     *
     * @param duties the value for T_ADMIN_ACCOUNT.DUTIES
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setDuties(String duties) {
        this.duties = duties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.ROLE_SUBSECTION
     *
     * @return the value of T_ADMIN_ACCOUNT.ROLE_SUBSECTION
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Long getRoleSubsection() {
        return roleSubsection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.ROLE_SUBSECTION
     *
     * @param roleSubsection the value for T_ADMIN_ACCOUNT.ROLE_SUBSECTION
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setRoleSubsection(Long roleSubsection) {
        this.roleSubsection = roleSubsection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.STATUS
     *
     * @return the value of T_ADMIN_ACCOUNT.STATUS
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.STATUS
     *
     * @param status the value for T_ADMIN_ACCOUNT.STATUS
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.POSITION_RANK
     *
     * @return the value of T_ADMIN_ACCOUNT.POSITION_RANK
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getPositionRank() {
        return positionRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.POSITION_RANK
     *
     * @param positionRank the value for T_ADMIN_ACCOUNT.POSITION_RANK
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setPositionRank(String positionRank) {
        this.positionRank = positionRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.SCORE
     *
     * @return the value of T_ADMIN_ACCOUNT.SCORE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.SCORE
     *
     * @param score the value for T_ADMIN_ACCOUNT.SCORE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.FROZEN_TIME
     *
     * @return the value of T_ADMIN_ACCOUNT.FROZEN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getFrozenTime() {
        return frozenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.FROZEN_TIME
     *
     * @param frozenTime the value for T_ADMIN_ACCOUNT.FROZEN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setFrozenTime(Date frozenTime) {
        this.frozenTime = frozenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.EHR_STAFF_ID
     *
     * @return the value of T_ADMIN_ACCOUNT.EHR_STAFF_ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Long getEhrStaffId() {
        return ehrStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.EHR_STAFF_ID
     *
     * @param ehrStaffId the value for T_ADMIN_ACCOUNT.EHR_STAFF_ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEhrStaffId(Long ehrStaffId) {
        this.ehrStaffId = ehrStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN_ACCOUNT.JOB_NUMBER
     *
     * @return the value of T_ADMIN_ACCOUNT.JOB_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN_ACCOUNT.JOB_NUMBER
     *
     * @param jobNumber the value for T_ADMIN_ACCOUNT.JOB_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }
}