package com.springboot.xp.dao.mysql.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdminAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public AdminAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmpIdIsNull() {
            addCriterion("EMP_ID is null");
            return (Criteria) this;
        }

        public Criteria andEmpIdIsNotNull() {
            addCriterion("EMP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEmpIdEqualTo(String value) {
            addCriterion("EMP_ID =", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotEqualTo(String value) {
            addCriterion("EMP_ID <>", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThan(String value) {
            addCriterion("EMP_ID >", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_ID >=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThan(String value) {
            addCriterion("EMP_ID <", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThanOrEqualTo(String value) {
            addCriterion("EMP_ID <=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLike(String value) {
            addCriterion("EMP_ID like", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotLike(String value) {
            addCriterion("EMP_ID not like", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdIn(List<String> values) {
            addCriterion("EMP_ID in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotIn(List<String> values) {
            addCriterion("EMP_ID not in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdBetween(String value1, String value2) {
            addCriterion("EMP_ID between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotBetween(String value1, String value2) {
            addCriterion("EMP_ID not between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNull() {
            addCriterion("EMP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNotNull() {
            addCriterion("EMP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNameEqualTo(String value) {
            addCriterion("EMP_NAME =", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotEqualTo(String value) {
            addCriterion("EMP_NAME <>", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThan(String value) {
            addCriterion("EMP_NAME >", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_NAME >=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThan(String value) {
            addCriterion("EMP_NAME <", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThanOrEqualTo(String value) {
            addCriterion("EMP_NAME <=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLike(String value) {
            addCriterion("EMP_NAME like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotLike(String value) {
            addCriterion("EMP_NAME not like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameIn(List<String> values) {
            addCriterion("EMP_NAME in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotIn(List<String> values) {
            addCriterion("EMP_NAME not in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameBetween(String value1, String value2) {
            addCriterion("EMP_NAME between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotBetween(String value1, String value2) {
            addCriterion("EMP_NAME not between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpEmailIsNull() {
            addCriterion("EMP_EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmpEmailIsNotNull() {
            addCriterion("EMP_EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmpEmailEqualTo(String value) {
            addCriterion("EMP_EMAIL =", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotEqualTo(String value) {
            addCriterion("EMP_EMAIL <>", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailGreaterThan(String value) {
            addCriterion("EMP_EMAIL >", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_EMAIL >=", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailLessThan(String value) {
            addCriterion("EMP_EMAIL <", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailLessThanOrEqualTo(String value) {
            addCriterion("EMP_EMAIL <=", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailLike(String value) {
            addCriterion("EMP_EMAIL like", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotLike(String value) {
            addCriterion("EMP_EMAIL not like", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailIn(List<String> values) {
            addCriterion("EMP_EMAIL in", values, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotIn(List<String> values) {
            addCriterion("EMP_EMAIL not in", values, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailBetween(String value1, String value2) {
            addCriterion("EMP_EMAIL between", value1, value2, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotBetween(String value1, String value2) {
            addCriterion("EMP_EMAIL not between", value1, value2, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpPwdIsNull() {
            addCriterion("EMP_PWD is null");
            return (Criteria) this;
        }

        public Criteria andEmpPwdIsNotNull() {
            addCriterion("EMP_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andEmpPwdEqualTo(String value) {
            addCriterion("EMP_PWD =", value, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdNotEqualTo(String value) {
            addCriterion("EMP_PWD <>", value, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdGreaterThan(String value) {
            addCriterion("EMP_PWD >", value, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_PWD >=", value, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdLessThan(String value) {
            addCriterion("EMP_PWD <", value, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdLessThanOrEqualTo(String value) {
            addCriterion("EMP_PWD <=", value, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdLike(String value) {
            addCriterion("EMP_PWD like", value, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdNotLike(String value) {
            addCriterion("EMP_PWD not like", value, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdIn(List<String> values) {
            addCriterion("EMP_PWD in", values, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdNotIn(List<String> values) {
            addCriterion("EMP_PWD not in", values, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdBetween(String value1, String value2) {
            addCriterion("EMP_PWD between", value1, value2, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPwdNotBetween(String value1, String value2) {
            addCriterion("EMP_PWD not between", value1, value2, "empPwd");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneIsNull() {
            addCriterion("EMP_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneIsNotNull() {
            addCriterion("EMP_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneEqualTo(String value) {
            addCriterion("EMP_PHONE =", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneNotEqualTo(String value) {
            addCriterion("EMP_PHONE <>", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneGreaterThan(String value) {
            addCriterion("EMP_PHONE >", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_PHONE >=", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneLessThan(String value) {
            addCriterion("EMP_PHONE <", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneLessThanOrEqualTo(String value) {
            addCriterion("EMP_PHONE <=", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneLike(String value) {
            addCriterion("EMP_PHONE like", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneNotLike(String value) {
            addCriterion("EMP_PHONE not like", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneIn(List<String> values) {
            addCriterion("EMP_PHONE in", values, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneNotIn(List<String> values) {
            addCriterion("EMP_PHONE not in", values, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneBetween(String value1, String value2) {
            addCriterion("EMP_PHONE between", value1, value2, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneNotBetween(String value1, String value2) {
            addCriterion("EMP_PHONE not between", value1, value2, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpMobileIsNull() {
            addCriterion("EMP_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andEmpMobileIsNotNull() {
            addCriterion("EMP_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andEmpMobileEqualTo(String value) {
            addCriterion("EMP_MOBILE =", value, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileNotEqualTo(String value) {
            addCriterion("EMP_MOBILE <>", value, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileGreaterThan(String value) {
            addCriterion("EMP_MOBILE >", value, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_MOBILE >=", value, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileLessThan(String value) {
            addCriterion("EMP_MOBILE <", value, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileLessThanOrEqualTo(String value) {
            addCriterion("EMP_MOBILE <=", value, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileLike(String value) {
            addCriterion("EMP_MOBILE like", value, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileNotLike(String value) {
            addCriterion("EMP_MOBILE not like", value, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileIn(List<String> values) {
            addCriterion("EMP_MOBILE in", values, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileNotIn(List<String> values) {
            addCriterion("EMP_MOBILE not in", values, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileBetween(String value1, String value2) {
            addCriterion("EMP_MOBILE between", value1, value2, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpMobileNotBetween(String value1, String value2) {
            addCriterion("EMP_MOBILE not between", value1, value2, "empMobile");
            return (Criteria) this;
        }

        public Criteria andEmpExtIsNull() {
            addCriterion("EMP_EXT is null");
            return (Criteria) this;
        }

        public Criteria andEmpExtIsNotNull() {
            addCriterion("EMP_EXT is not null");
            return (Criteria) this;
        }

        public Criteria andEmpExtEqualTo(String value) {
            addCriterion("EMP_EXT =", value, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtNotEqualTo(String value) {
            addCriterion("EMP_EXT <>", value, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtGreaterThan(String value) {
            addCriterion("EMP_EXT >", value, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_EXT >=", value, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtLessThan(String value) {
            addCriterion("EMP_EXT <", value, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtLessThanOrEqualTo(String value) {
            addCriterion("EMP_EXT <=", value, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtLike(String value) {
            addCriterion("EMP_EXT like", value, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtNotLike(String value) {
            addCriterion("EMP_EXT not like", value, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtIn(List<String> values) {
            addCriterion("EMP_EXT in", values, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtNotIn(List<String> values) {
            addCriterion("EMP_EXT not in", values, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtBetween(String value1, String value2) {
            addCriterion("EMP_EXT between", value1, value2, "empExt");
            return (Criteria) this;
        }

        public Criteria andEmpExtNotBetween(String value1, String value2) {
            addCriterion("EMP_EXT not between", value1, value2, "empExt");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIsNull() {
            addCriterion("ACCOUNT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIsNotNull() {
            addCriterion("ACCOUNT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAccountTypeEqualTo(String value) {
            addCriterion("ACCOUNT_TYPE =", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotEqualTo(String value) {
            addCriterion("ACCOUNT_TYPE <>", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeGreaterThan(String value) {
            addCriterion("ACCOUNT_TYPE >", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_TYPE >=", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLessThan(String value) {
            addCriterion("ACCOUNT_TYPE <", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_TYPE <=", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeLike(String value) {
            addCriterion("ACCOUNT_TYPE like", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotLike(String value) {
            addCriterion("ACCOUNT_TYPE not like", value, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeIn(List<String> values) {
            addCriterion("ACCOUNT_TYPE in", values, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotIn(List<String> values) {
            addCriterion("ACCOUNT_TYPE not in", values, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeBetween(String value1, String value2) {
            addCriterion("ACCOUNT_TYPE between", value1, value2, "accountType");
            return (Criteria) this;
        }

        public Criteria andAccountTypeNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT_TYPE not between", value1, value2, "accountType");
            return (Criteria) this;
        }

        public Criteria andIsLiveIsNull() {
            addCriterion("IS_LIVE is null");
            return (Criteria) this;
        }

        public Criteria andIsLiveIsNotNull() {
            addCriterion("IS_LIVE is not null");
            return (Criteria) this;
        }

        public Criteria andIsLiveEqualTo(String value) {
            addCriterion("IS_LIVE =", value, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveNotEqualTo(String value) {
            addCriterion("IS_LIVE <>", value, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveGreaterThan(String value) {
            addCriterion("IS_LIVE >", value, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveGreaterThanOrEqualTo(String value) {
            addCriterion("IS_LIVE >=", value, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveLessThan(String value) {
            addCriterion("IS_LIVE <", value, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveLessThanOrEqualTo(String value) {
            addCriterion("IS_LIVE <=", value, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveLike(String value) {
            addCriterion("IS_LIVE like", value, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveNotLike(String value) {
            addCriterion("IS_LIVE not like", value, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveIn(List<String> values) {
            addCriterion("IS_LIVE in", values, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveNotIn(List<String> values) {
            addCriterion("IS_LIVE not in", values, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveBetween(String value1, String value2) {
            addCriterion("IS_LIVE between", value1, value2, "isLive");
            return (Criteria) this;
        }

        public Criteria andIsLiveNotBetween(String value1, String value2) {
            addCriterion("IS_LIVE not between", value1, value2, "isLive");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateDttmIsNull() {
            addCriterion("CREATE_DTTM is null");
            return (Criteria) this;
        }

        public Criteria andCreateDttmIsNotNull() {
            addCriterion("CREATE_DTTM is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDttmEqualTo(Date value) {
            addCriterion("CREATE_DTTM =", value, "createDttm");
            return (Criteria) this;
        }

        public Criteria andCreateDttmNotEqualTo(Date value) {
            addCriterion("CREATE_DTTM <>", value, "createDttm");
            return (Criteria) this;
        }

        public Criteria andCreateDttmGreaterThan(Date value) {
            addCriterion("CREATE_DTTM >", value, "createDttm");
            return (Criteria) this;
        }

        public Criteria andCreateDttmGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DTTM >=", value, "createDttm");
            return (Criteria) this;
        }

        public Criteria andCreateDttmLessThan(Date value) {
            addCriterion("CREATE_DTTM <", value, "createDttm");
            return (Criteria) this;
        }

        public Criteria andCreateDttmLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DTTM <=", value, "createDttm");
            return (Criteria) this;
        }

        public Criteria andCreateDttmIn(List<Date> values) {
            addCriterion("CREATE_DTTM in", values, "createDttm");
            return (Criteria) this;
        }

        public Criteria andCreateDttmNotIn(List<Date> values) {
            addCriterion("CREATE_DTTM not in", values, "createDttm");
            return (Criteria) this;
        }

        public Criteria andCreateDttmBetween(Date value1, Date value2) {
            addCriterion("CREATE_DTTM between", value1, value2, "createDttm");
            return (Criteria) this;
        }

        public Criteria andCreateDttmNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DTTM not between", value1, value2, "createDttm");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("UPDATER is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("UPDATER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("UPDATER =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("UPDATER <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("UPDATER >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("UPDATER <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("UPDATER <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("UPDATER like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("UPDATER not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("UPDATER in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("UPDATER not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("UPDATER between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("UPDATER not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmIsNull() {
            addCriterion("UPDATE_DTTM is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmIsNotNull() {
            addCriterion("UPDATE_DTTM is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmEqualTo(Date value) {
            addCriterion("UPDATE_DTTM =", value, "updateDttm");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmNotEqualTo(Date value) {
            addCriterion("UPDATE_DTTM <>", value, "updateDttm");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmGreaterThan(Date value) {
            addCriterion("UPDATE_DTTM >", value, "updateDttm");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DTTM >=", value, "updateDttm");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmLessThan(Date value) {
            addCriterion("UPDATE_DTTM <", value, "updateDttm");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DTTM <=", value, "updateDttm");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmIn(List<Date> values) {
            addCriterion("UPDATE_DTTM in", values, "updateDttm");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmNotIn(List<Date> values) {
            addCriterion("UPDATE_DTTM not in", values, "updateDttm");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DTTM between", value1, value2, "updateDttm");
            return (Criteria) this;
        }

        public Criteria andUpdateDttmNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DTTM not between", value1, value2, "updateDttm");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyIsNull() {
            addCriterion("AM_PAY_MONEY is null");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyIsNotNull() {
            addCriterion("AM_PAY_MONEY is not null");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyEqualTo(Long value) {
            addCriterion("AM_PAY_MONEY =", value, "amPayMoney");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyNotEqualTo(Long value) {
            addCriterion("AM_PAY_MONEY <>", value, "amPayMoney");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyGreaterThan(Long value) {
            addCriterion("AM_PAY_MONEY >", value, "amPayMoney");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyGreaterThanOrEqualTo(Long value) {
            addCriterion("AM_PAY_MONEY >=", value, "amPayMoney");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyLessThan(Long value) {
            addCriterion("AM_PAY_MONEY <", value, "amPayMoney");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyLessThanOrEqualTo(Long value) {
            addCriterion("AM_PAY_MONEY <=", value, "amPayMoney");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyIn(List<Long> values) {
            addCriterion("AM_PAY_MONEY in", values, "amPayMoney");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyNotIn(List<Long> values) {
            addCriterion("AM_PAY_MONEY not in", values, "amPayMoney");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyBetween(Long value1, Long value2) {
            addCriterion("AM_PAY_MONEY between", value1, value2, "amPayMoney");
            return (Criteria) this;
        }

        public Criteria andAmPayMoneyNotBetween(Long value1, Long value2) {
            addCriterion("AM_PAY_MONEY not between", value1, value2, "amPayMoney");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumIsNull() {
            addCriterion("AM_ENTRY_CONFIRM_NUM is null");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumIsNotNull() {
            addCriterion("AM_ENTRY_CONFIRM_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumEqualTo(Long value) {
            addCriterion("AM_ENTRY_CONFIRM_NUM =", value, "amEntryConfirmNum");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumNotEqualTo(Long value) {
            addCriterion("AM_ENTRY_CONFIRM_NUM <>", value, "amEntryConfirmNum");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumGreaterThan(Long value) {
            addCriterion("AM_ENTRY_CONFIRM_NUM >", value, "amEntryConfirmNum");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumGreaterThanOrEqualTo(Long value) {
            addCriterion("AM_ENTRY_CONFIRM_NUM >=", value, "amEntryConfirmNum");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumLessThan(Long value) {
            addCriterion("AM_ENTRY_CONFIRM_NUM <", value, "amEntryConfirmNum");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumLessThanOrEqualTo(Long value) {
            addCriterion("AM_ENTRY_CONFIRM_NUM <=", value, "amEntryConfirmNum");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumIn(List<Long> values) {
            addCriterion("AM_ENTRY_CONFIRM_NUM in", values, "amEntryConfirmNum");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumNotIn(List<Long> values) {
            addCriterion("AM_ENTRY_CONFIRM_NUM not in", values, "amEntryConfirmNum");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumBetween(Long value1, Long value2) {
            addCriterion("AM_ENTRY_CONFIRM_NUM between", value1, value2, "amEntryConfirmNum");
            return (Criteria) this;
        }

        public Criteria andAmEntryConfirmNumNotBetween(Long value1, Long value2) {
            addCriterion("AM_ENTRY_CONFIRM_NUM not between", value1, value2, "amEntryConfirmNum");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountIsNull() {
            addCriterion("PAYMENTS_AMOUNT_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountIsNotNull() {
            addCriterion("PAYMENTS_AMOUNT_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountEqualTo(Long value) {
            addCriterion("PAYMENTS_AMOUNT_COUNT =", value, "paymentsAmountCount");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountNotEqualTo(Long value) {
            addCriterion("PAYMENTS_AMOUNT_COUNT <>", value, "paymentsAmountCount");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountGreaterThan(Long value) {
            addCriterion("PAYMENTS_AMOUNT_COUNT >", value, "paymentsAmountCount");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountGreaterThanOrEqualTo(Long value) {
            addCriterion("PAYMENTS_AMOUNT_COUNT >=", value, "paymentsAmountCount");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountLessThan(Long value) {
            addCriterion("PAYMENTS_AMOUNT_COUNT <", value, "paymentsAmountCount");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountLessThanOrEqualTo(Long value) {
            addCriterion("PAYMENTS_AMOUNT_COUNT <=", value, "paymentsAmountCount");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountIn(List<Long> values) {
            addCriterion("PAYMENTS_AMOUNT_COUNT in", values, "paymentsAmountCount");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountNotIn(List<Long> values) {
            addCriterion("PAYMENTS_AMOUNT_COUNT not in", values, "paymentsAmountCount");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountBetween(Long value1, Long value2) {
            addCriterion("PAYMENTS_AMOUNT_COUNT between", value1, value2, "paymentsAmountCount");
            return (Criteria) this;
        }

        public Criteria andPaymentsAmountCountNotBetween(Long value1, Long value2) {
            addCriterion("PAYMENTS_AMOUNT_COUNT not between", value1, value2, "paymentsAmountCount");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumIsNull() {
            addCriterion("PAYMENTS_NUM is null");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumIsNotNull() {
            addCriterion("PAYMENTS_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumEqualTo(Long value) {
            addCriterion("PAYMENTS_NUM =", value, "paymentsNum");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumNotEqualTo(Long value) {
            addCriterion("PAYMENTS_NUM <>", value, "paymentsNum");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumGreaterThan(Long value) {
            addCriterion("PAYMENTS_NUM >", value, "paymentsNum");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumGreaterThanOrEqualTo(Long value) {
            addCriterion("PAYMENTS_NUM >=", value, "paymentsNum");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumLessThan(Long value) {
            addCriterion("PAYMENTS_NUM <", value, "paymentsNum");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumLessThanOrEqualTo(Long value) {
            addCriterion("PAYMENTS_NUM <=", value, "paymentsNum");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumIn(List<Long> values) {
            addCriterion("PAYMENTS_NUM in", values, "paymentsNum");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumNotIn(List<Long> values) {
            addCriterion("PAYMENTS_NUM not in", values, "paymentsNum");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumBetween(Long value1, Long value2) {
            addCriterion("PAYMENTS_NUM between", value1, value2, "paymentsNum");
            return (Criteria) this;
        }

        public Criteria andPaymentsNumNotBetween(Long value1, Long value2) {
            addCriterion("PAYMENTS_NUM not between", value1, value2, "paymentsNum");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeIsNull() {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME is null");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeIsNotNull() {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME is not null");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeEqualTo(Date value) {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME =", value, "jobDynamicInformationReadtime");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeNotEqualTo(Date value) {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME <>", value, "jobDynamicInformationReadtime");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeGreaterThan(Date value) {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME >", value, "jobDynamicInformationReadtime");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME >=", value, "jobDynamicInformationReadtime");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeLessThan(Date value) {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME <", value, "jobDynamicInformationReadtime");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeLessThanOrEqualTo(Date value) {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME <=", value, "jobDynamicInformationReadtime");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeIn(List<Date> values) {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME in", values, "jobDynamicInformationReadtime");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeNotIn(List<Date> values) {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME not in", values, "jobDynamicInformationReadtime");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeBetween(Date value1, Date value2) {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME between", value1, value2, "jobDynamicInformationReadtime");
            return (Criteria) this;
        }

        public Criteria andJobDynamicInformationReadtimeNotBetween(Date value1, Date value2) {
            addCriterion("JOB_DYNAMIC_INFORMATION_READTIME not between", value1, value2, "jobDynamicInformationReadtime");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeIsNull() {
            addCriterion("CANDIDATE_DYNAMIC_READTIME is null");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeIsNotNull() {
            addCriterion("CANDIDATE_DYNAMIC_READTIME is not null");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeEqualTo(Date value) {
            addCriterion("CANDIDATE_DYNAMIC_READTIME =", value, "candidateDynamicReadtime");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeNotEqualTo(Date value) {
            addCriterion("CANDIDATE_DYNAMIC_READTIME <>", value, "candidateDynamicReadtime");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeGreaterThan(Date value) {
            addCriterion("CANDIDATE_DYNAMIC_READTIME >", value, "candidateDynamicReadtime");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CANDIDATE_DYNAMIC_READTIME >=", value, "candidateDynamicReadtime");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeLessThan(Date value) {
            addCriterion("CANDIDATE_DYNAMIC_READTIME <", value, "candidateDynamicReadtime");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeLessThanOrEqualTo(Date value) {
            addCriterion("CANDIDATE_DYNAMIC_READTIME <=", value, "candidateDynamicReadtime");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeIn(List<Date> values) {
            addCriterion("CANDIDATE_DYNAMIC_READTIME in", values, "candidateDynamicReadtime");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeNotIn(List<Date> values) {
            addCriterion("CANDIDATE_DYNAMIC_READTIME not in", values, "candidateDynamicReadtime");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeBetween(Date value1, Date value2) {
            addCriterion("CANDIDATE_DYNAMIC_READTIME between", value1, value2, "candidateDynamicReadtime");
            return (Criteria) this;
        }

        public Criteria andCandidateDynamicReadtimeNotBetween(Date value1, Date value2) {
            addCriterion("CANDIDATE_DYNAMIC_READTIME not between", value1, value2, "candidateDynamicReadtime");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeIsNull() {
            addCriterion("JOB_CONMUNICATION_TIME is null");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeIsNotNull() {
            addCriterion("JOB_CONMUNICATION_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeEqualTo(Date value) {
            addCriterion("JOB_CONMUNICATION_TIME =", value, "jobConmunicationTime");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeNotEqualTo(Date value) {
            addCriterion("JOB_CONMUNICATION_TIME <>", value, "jobConmunicationTime");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeGreaterThan(Date value) {
            addCriterion("JOB_CONMUNICATION_TIME >", value, "jobConmunicationTime");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("JOB_CONMUNICATION_TIME >=", value, "jobConmunicationTime");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeLessThan(Date value) {
            addCriterion("JOB_CONMUNICATION_TIME <", value, "jobConmunicationTime");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeLessThanOrEqualTo(Date value) {
            addCriterion("JOB_CONMUNICATION_TIME <=", value, "jobConmunicationTime");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeIn(List<Date> values) {
            addCriterion("JOB_CONMUNICATION_TIME in", values, "jobConmunicationTime");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeNotIn(List<Date> values) {
            addCriterion("JOB_CONMUNICATION_TIME not in", values, "jobConmunicationTime");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeBetween(Date value1, Date value2) {
            addCriterion("JOB_CONMUNICATION_TIME between", value1, value2, "jobConmunicationTime");
            return (Criteria) this;
        }

        public Criteria andJobConmunicationTimeNotBetween(Date value1, Date value2) {
            addCriterion("JOB_CONMUNICATION_TIME not between", value1, value2, "jobConmunicationTime");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("URL in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("URL not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeIsNull() {
            addCriterion("PREV_LOGIN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeIsNotNull() {
            addCriterion("PREV_LOGIN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeEqualTo(Date value) {
            addCriterion("PREV_LOGIN_TIME =", value, "prevLoginTime");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeNotEqualTo(Date value) {
            addCriterion("PREV_LOGIN_TIME <>", value, "prevLoginTime");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeGreaterThan(Date value) {
            addCriterion("PREV_LOGIN_TIME >", value, "prevLoginTime");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PREV_LOGIN_TIME >=", value, "prevLoginTime");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeLessThan(Date value) {
            addCriterion("PREV_LOGIN_TIME <", value, "prevLoginTime");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("PREV_LOGIN_TIME <=", value, "prevLoginTime");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeIn(List<Date> values) {
            addCriterion("PREV_LOGIN_TIME in", values, "prevLoginTime");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeNotIn(List<Date> values) {
            addCriterion("PREV_LOGIN_TIME not in", values, "prevLoginTime");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeBetween(Date value1, Date value2) {
            addCriterion("PREV_LOGIN_TIME between", value1, value2, "prevLoginTime");
            return (Criteria) this;
        }

        public Criteria andPrevLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("PREV_LOGIN_TIME not between", value1, value2, "prevLoginTime");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeIsNull() {
            addCriterion("NOW_LOGIN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeIsNotNull() {
            addCriterion("NOW_LOGIN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeEqualTo(Date value) {
            addCriterion("NOW_LOGIN_TIME =", value, "nowLoginTime");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeNotEqualTo(Date value) {
            addCriterion("NOW_LOGIN_TIME <>", value, "nowLoginTime");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeGreaterThan(Date value) {
            addCriterion("NOW_LOGIN_TIME >", value, "nowLoginTime");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("NOW_LOGIN_TIME >=", value, "nowLoginTime");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeLessThan(Date value) {
            addCriterion("NOW_LOGIN_TIME <", value, "nowLoginTime");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("NOW_LOGIN_TIME <=", value, "nowLoginTime");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeIn(List<Date> values) {
            addCriterion("NOW_LOGIN_TIME in", values, "nowLoginTime");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeNotIn(List<Date> values) {
            addCriterion("NOW_LOGIN_TIME not in", values, "nowLoginTime");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeBetween(Date value1, Date value2) {
            addCriterion("NOW_LOGIN_TIME between", value1, value2, "nowLoginTime");
            return (Criteria) this;
        }

        public Criteria andNowLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("NOW_LOGIN_TIME not between", value1, value2, "nowLoginTime");
            return (Criteria) this;
        }

        public Criteria andEmpWechatIsNull() {
            addCriterion("EMP_WECHAT is null");
            return (Criteria) this;
        }

        public Criteria andEmpWechatIsNotNull() {
            addCriterion("EMP_WECHAT is not null");
            return (Criteria) this;
        }

        public Criteria andEmpWechatEqualTo(String value) {
            addCriterion("EMP_WECHAT =", value, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatNotEqualTo(String value) {
            addCriterion("EMP_WECHAT <>", value, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatGreaterThan(String value) {
            addCriterion("EMP_WECHAT >", value, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_WECHAT >=", value, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatLessThan(String value) {
            addCriterion("EMP_WECHAT <", value, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatLessThanOrEqualTo(String value) {
            addCriterion("EMP_WECHAT <=", value, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatLike(String value) {
            addCriterion("EMP_WECHAT like", value, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatNotLike(String value) {
            addCriterion("EMP_WECHAT not like", value, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatIn(List<String> values) {
            addCriterion("EMP_WECHAT in", values, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatNotIn(List<String> values) {
            addCriterion("EMP_WECHAT not in", values, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatBetween(String value1, String value2) {
            addCriterion("EMP_WECHAT between", value1, value2, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpWechatNotBetween(String value1, String value2) {
            addCriterion("EMP_WECHAT not between", value1, value2, "empWechat");
            return (Criteria) this;
        }

        public Criteria andEmpQqIsNull() {
            addCriterion("EMP_QQ is null");
            return (Criteria) this;
        }

        public Criteria andEmpQqIsNotNull() {
            addCriterion("EMP_QQ is not null");
            return (Criteria) this;
        }

        public Criteria andEmpQqEqualTo(String value) {
            addCriterion("EMP_QQ =", value, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqNotEqualTo(String value) {
            addCriterion("EMP_QQ <>", value, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqGreaterThan(String value) {
            addCriterion("EMP_QQ >", value, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqGreaterThanOrEqualTo(String value) {
            addCriterion("EMP_QQ >=", value, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqLessThan(String value) {
            addCriterion("EMP_QQ <", value, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqLessThanOrEqualTo(String value) {
            addCriterion("EMP_QQ <=", value, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqLike(String value) {
            addCriterion("EMP_QQ like", value, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqNotLike(String value) {
            addCriterion("EMP_QQ not like", value, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqIn(List<String> values) {
            addCriterion("EMP_QQ in", values, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqNotIn(List<String> values) {
            addCriterion("EMP_QQ not in", values, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqBetween(String value1, String value2) {
            addCriterion("EMP_QQ between", value1, value2, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpQqNotBetween(String value1, String value2) {
            addCriterion("EMP_QQ not between", value1, value2, "empQq");
            return (Criteria) this;
        }

        public Criteria andEmpLevelIsNull() {
            addCriterion("EMP_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andEmpLevelIsNotNull() {
            addCriterion("EMP_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andEmpLevelEqualTo(Integer value) {
            addCriterion("EMP_LEVEL =", value, "empLevel");
            return (Criteria) this;
        }

        public Criteria andEmpLevelNotEqualTo(Integer value) {
            addCriterion("EMP_LEVEL <>", value, "empLevel");
            return (Criteria) this;
        }

        public Criteria andEmpLevelGreaterThan(Integer value) {
            addCriterion("EMP_LEVEL >", value, "empLevel");
            return (Criteria) this;
        }

        public Criteria andEmpLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("EMP_LEVEL >=", value, "empLevel");
            return (Criteria) this;
        }

        public Criteria andEmpLevelLessThan(Integer value) {
            addCriterion("EMP_LEVEL <", value, "empLevel");
            return (Criteria) this;
        }

        public Criteria andEmpLevelLessThanOrEqualTo(Integer value) {
            addCriterion("EMP_LEVEL <=", value, "empLevel");
            return (Criteria) this;
        }

        public Criteria andEmpLevelIn(List<Integer> values) {
            addCriterion("EMP_LEVEL in", values, "empLevel");
            return (Criteria) this;
        }

        public Criteria andEmpLevelNotIn(List<Integer> values) {
            addCriterion("EMP_LEVEL not in", values, "empLevel");
            return (Criteria) this;
        }

        public Criteria andEmpLevelBetween(Integer value1, Integer value2) {
            addCriterion("EMP_LEVEL between", value1, value2, "empLevel");
            return (Criteria) this;
        }

        public Criteria andEmpLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("EMP_LEVEL not between", value1, value2, "empLevel");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("ROLE_ID is null");
            return (Criteria) this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("ROLE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRoleIdEqualTo(Long value) {
            addCriterion("ROLE_ID =", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotEqualTo(Long value) {
            addCriterion("ROLE_ID <>", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThan(Long value) {
            addCriterion("ROLE_ID >", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ROLE_ID >=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThan(Long value) {
            addCriterion("ROLE_ID <", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(Long value) {
            addCriterion("ROLE_ID <=", value, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdIn(List<Long> values) {
            addCriterion("ROLE_ID in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotIn(List<Long> values) {
            addCriterion("ROLE_ID not in", values, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdBetween(Long value1, Long value2) {
            addCriterion("ROLE_ID between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andRoleIdNotBetween(Long value1, Long value2) {
            addCriterion("ROLE_ID not between", value1, value2, "roleId");
            return (Criteria) this;
        }

        public Criteria andDutiesIsNull() {
            addCriterion("DUTIES is null");
            return (Criteria) this;
        }

        public Criteria andDutiesIsNotNull() {
            addCriterion("DUTIES is not null");
            return (Criteria) this;
        }

        public Criteria andDutiesEqualTo(String value) {
            addCriterion("DUTIES =", value, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesNotEqualTo(String value) {
            addCriterion("DUTIES <>", value, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesGreaterThan(String value) {
            addCriterion("DUTIES >", value, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesGreaterThanOrEqualTo(String value) {
            addCriterion("DUTIES >=", value, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesLessThan(String value) {
            addCriterion("DUTIES <", value, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesLessThanOrEqualTo(String value) {
            addCriterion("DUTIES <=", value, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesLike(String value) {
            addCriterion("DUTIES like", value, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesNotLike(String value) {
            addCriterion("DUTIES not like", value, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesIn(List<String> values) {
            addCriterion("DUTIES in", values, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesNotIn(List<String> values) {
            addCriterion("DUTIES not in", values, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesBetween(String value1, String value2) {
            addCriterion("DUTIES between", value1, value2, "duties");
            return (Criteria) this;
        }

        public Criteria andDutiesNotBetween(String value1, String value2) {
            addCriterion("DUTIES not between", value1, value2, "duties");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionIsNull() {
            addCriterion("ROLE_SUBSECTION is null");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionIsNotNull() {
            addCriterion("ROLE_SUBSECTION is not null");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionEqualTo(Long value) {
            addCriterion("ROLE_SUBSECTION =", value, "roleSubsection");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionNotEqualTo(Long value) {
            addCriterion("ROLE_SUBSECTION <>", value, "roleSubsection");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionGreaterThan(Long value) {
            addCriterion("ROLE_SUBSECTION >", value, "roleSubsection");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionGreaterThanOrEqualTo(Long value) {
            addCriterion("ROLE_SUBSECTION >=", value, "roleSubsection");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionLessThan(Long value) {
            addCriterion("ROLE_SUBSECTION <", value, "roleSubsection");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionLessThanOrEqualTo(Long value) {
            addCriterion("ROLE_SUBSECTION <=", value, "roleSubsection");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionIn(List<Long> values) {
            addCriterion("ROLE_SUBSECTION in", values, "roleSubsection");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionNotIn(List<Long> values) {
            addCriterion("ROLE_SUBSECTION not in", values, "roleSubsection");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionBetween(Long value1, Long value2) {
            addCriterion("ROLE_SUBSECTION between", value1, value2, "roleSubsection");
            return (Criteria) this;
        }

        public Criteria andRoleSubsectionNotBetween(Long value1, Long value2) {
            addCriterion("ROLE_SUBSECTION not between", value1, value2, "roleSubsection");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPositionRankIsNull() {
            addCriterion("POSITION_RANK is null");
            return (Criteria) this;
        }

        public Criteria andPositionRankIsNotNull() {
            addCriterion("POSITION_RANK is not null");
            return (Criteria) this;
        }

        public Criteria andPositionRankEqualTo(String value) {
            addCriterion("POSITION_RANK =", value, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankNotEqualTo(String value) {
            addCriterion("POSITION_RANK <>", value, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankGreaterThan(String value) {
            addCriterion("POSITION_RANK >", value, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankGreaterThanOrEqualTo(String value) {
            addCriterion("POSITION_RANK >=", value, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankLessThan(String value) {
            addCriterion("POSITION_RANK <", value, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankLessThanOrEqualTo(String value) {
            addCriterion("POSITION_RANK <=", value, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankLike(String value) {
            addCriterion("POSITION_RANK like", value, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankNotLike(String value) {
            addCriterion("POSITION_RANK not like", value, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankIn(List<String> values) {
            addCriterion("POSITION_RANK in", values, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankNotIn(List<String> values) {
            addCriterion("POSITION_RANK not in", values, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankBetween(String value1, String value2) {
            addCriterion("POSITION_RANK between", value1, value2, "positionRank");
            return (Criteria) this;
        }

        public Criteria andPositionRankNotBetween(String value1, String value2) {
            addCriterion("POSITION_RANK not between", value1, value2, "positionRank");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("SCORE is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("SCORE is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Double value) {
            addCriterion("SCORE =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Double value) {
            addCriterion("SCORE <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Double value) {
            addCriterion("SCORE >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Double value) {
            addCriterion("SCORE >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Double value) {
            addCriterion("SCORE <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Double value) {
            addCriterion("SCORE <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Double> values) {
            addCriterion("SCORE in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Double> values) {
            addCriterion("SCORE not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Double value1, Double value2) {
            addCriterion("SCORE between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Double value1, Double value2) {
            addCriterion("SCORE not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeIsNull() {
            addCriterion("FROZEN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeIsNotNull() {
            addCriterion("FROZEN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeEqualTo(Date value) {
            addCriterion("FROZEN_TIME =", value, "frozenTime");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeNotEqualTo(Date value) {
            addCriterion("FROZEN_TIME <>", value, "frozenTime");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeGreaterThan(Date value) {
            addCriterion("FROZEN_TIME >", value, "frozenTime");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("FROZEN_TIME >=", value, "frozenTime");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeLessThan(Date value) {
            addCriterion("FROZEN_TIME <", value, "frozenTime");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeLessThanOrEqualTo(Date value) {
            addCriterion("FROZEN_TIME <=", value, "frozenTime");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeIn(List<Date> values) {
            addCriterion("FROZEN_TIME in", values, "frozenTime");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeNotIn(List<Date> values) {
            addCriterion("FROZEN_TIME not in", values, "frozenTime");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeBetween(Date value1, Date value2) {
            addCriterion("FROZEN_TIME between", value1, value2, "frozenTime");
            return (Criteria) this;
        }

        public Criteria andFrozenTimeNotBetween(Date value1, Date value2) {
            addCriterion("FROZEN_TIME not between", value1, value2, "frozenTime");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdIsNull() {
            addCriterion("EHR_STAFF_ID is null");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdIsNotNull() {
            addCriterion("EHR_STAFF_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdEqualTo(Long value) {
            addCriterion("EHR_STAFF_ID =", value, "ehrStaffId");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdNotEqualTo(Long value) {
            addCriterion("EHR_STAFF_ID <>", value, "ehrStaffId");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdGreaterThan(Long value) {
            addCriterion("EHR_STAFF_ID >", value, "ehrStaffId");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdGreaterThanOrEqualTo(Long value) {
            addCriterion("EHR_STAFF_ID >=", value, "ehrStaffId");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdLessThan(Long value) {
            addCriterion("EHR_STAFF_ID <", value, "ehrStaffId");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdLessThanOrEqualTo(Long value) {
            addCriterion("EHR_STAFF_ID <=", value, "ehrStaffId");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdIn(List<Long> values) {
            addCriterion("EHR_STAFF_ID in", values, "ehrStaffId");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdNotIn(List<Long> values) {
            addCriterion("EHR_STAFF_ID not in", values, "ehrStaffId");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdBetween(Long value1, Long value2) {
            addCriterion("EHR_STAFF_ID between", value1, value2, "ehrStaffId");
            return (Criteria) this;
        }

        public Criteria andEhrStaffIdNotBetween(Long value1, Long value2) {
            addCriterion("EHR_STAFF_ID not between", value1, value2, "ehrStaffId");
            return (Criteria) this;
        }

        public Criteria andJobNumberIsNull() {
            addCriterion("JOB_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andJobNumberIsNotNull() {
            addCriterion("JOB_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andJobNumberEqualTo(String value) {
            addCriterion("JOB_NUMBER =", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberNotEqualTo(String value) {
            addCriterion("JOB_NUMBER <>", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberGreaterThan(String value) {
            addCriterion("JOB_NUMBER >", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_NUMBER >=", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberLessThan(String value) {
            addCriterion("JOB_NUMBER <", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberLessThanOrEqualTo(String value) {
            addCriterion("JOB_NUMBER <=", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberLike(String value) {
            addCriterion("JOB_NUMBER like", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberNotLike(String value) {
            addCriterion("JOB_NUMBER not like", value, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberIn(List<String> values) {
            addCriterion("JOB_NUMBER in", values, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberNotIn(List<String> values) {
            addCriterion("JOB_NUMBER not in", values, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberBetween(String value1, String value2) {
            addCriterion("JOB_NUMBER between", value1, value2, "jobNumber");
            return (Criteria) this;
        }

        public Criteria andJobNumberNotBetween(String value1, String value2) {
            addCriterion("JOB_NUMBER not between", value1, value2, "jobNumber");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 18 14:06:16 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_ADMIN_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}