package com.springboot.xp.dao.mysql.model;

import java.util.Date;

public class GwAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_NAME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String gwName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.NICKNAME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_EMAIL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String gwEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_PHONE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String gwPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_PWD
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String gwPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.HISTORY_COIN_BALANCE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Integer historyCoinBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.PENDING_BALANCE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Integer pendingBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.IS_LIVE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String isLive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.ENTRY_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date entryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.DEPARTURE_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date departureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.CREATOR
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.CREATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date createDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.UPDATER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.UPDATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date updateDttm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_ENTRY_CONFIRM_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Long gwEntryConfirmNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_PAY_MONEY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Long gwPayMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GET_COLUMN_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Integer getColumnNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.JOB_DYNAMIC_INFORMATION_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date jobDynamicInformationReadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.CANDIDATE_DYNAMIC_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date candidateDynamicReadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.JOB_CONMUNICATE_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date jobConmunicateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.HUNT_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Integer huntNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.POSITION_RANK
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Integer positionRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_TYPE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Integer gwType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_LEVEL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Integer gwLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.URL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_CITY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String gwCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.PREV_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date prevLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.IS_INSIDE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String isInside;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.ROLE_CODE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.NOW_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Date nowLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.RECOMMENF_QUALITY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String recommenfQuality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.SERVE_QUALITY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String serveQuality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_TELEPHONE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String gwTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.EXTENSION_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String extensionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.JOB_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String jobNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_WECHAT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String gwWechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GW_QQ
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String gwQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.SELF_INTRODUCE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private String selfIntroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_GW_ACCOUNT.GENDER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    private Integer gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.ID
     *
     * @return the value of T_GW_ACCOUNT.ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.ID
     *
     * @param id the value for T_GW_ACCOUNT.ID
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_NAME
     *
     * @return the value of T_GW_ACCOUNT.GW_NAME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getGwName() {
        return gwName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_NAME
     *
     * @param gwName the value for T_GW_ACCOUNT.GW_NAME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwName(String gwName) {
        this.gwName = gwName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.NICKNAME
     *
     * @return the value of T_GW_ACCOUNT.NICKNAME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.NICKNAME
     *
     * @param nickname the value for T_GW_ACCOUNT.NICKNAME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_EMAIL
     *
     * @return the value of T_GW_ACCOUNT.GW_EMAIL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getGwEmail() {
        return gwEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_EMAIL
     *
     * @param gwEmail the value for T_GW_ACCOUNT.GW_EMAIL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwEmail(String gwEmail) {
        this.gwEmail = gwEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_PHONE
     *
     * @return the value of T_GW_ACCOUNT.GW_PHONE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getGwPhone() {
        return gwPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_PHONE
     *
     * @param gwPhone the value for T_GW_ACCOUNT.GW_PHONE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwPhone(String gwPhone) {
        this.gwPhone = gwPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_PWD
     *
     * @return the value of T_GW_ACCOUNT.GW_PWD
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getGwPwd() {
        return gwPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_PWD
     *
     * @param gwPwd the value for T_GW_ACCOUNT.GW_PWD
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwPwd(String gwPwd) {
        this.gwPwd = gwPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.HISTORY_COIN_BALANCE
     *
     * @return the value of T_GW_ACCOUNT.HISTORY_COIN_BALANCE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Integer getHistoryCoinBalance() {
        return historyCoinBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.HISTORY_COIN_BALANCE
     *
     * @param historyCoinBalance the value for T_GW_ACCOUNT.HISTORY_COIN_BALANCE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setHistoryCoinBalance(Integer historyCoinBalance) {
        this.historyCoinBalance = historyCoinBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.PENDING_BALANCE
     *
     * @return the value of T_GW_ACCOUNT.PENDING_BALANCE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Integer getPendingBalance() {
        return pendingBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.PENDING_BALANCE
     *
     * @param pendingBalance the value for T_GW_ACCOUNT.PENDING_BALANCE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setPendingBalance(Integer pendingBalance) {
        this.pendingBalance = pendingBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.IS_LIVE
     *
     * @return the value of T_GW_ACCOUNT.IS_LIVE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getIsLive() {
        return isLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.IS_LIVE
     *
     * @param isLive the value for T_GW_ACCOUNT.IS_LIVE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setIsLive(String isLive) {
        this.isLive = isLive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.ENTRY_TIME
     *
     * @return the value of T_GW_ACCOUNT.ENTRY_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.ENTRY_TIME
     *
     * @param entryTime the value for T_GW_ACCOUNT.ENTRY_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.DEPARTURE_TIME
     *
     * @return the value of T_GW_ACCOUNT.DEPARTURE_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getDepartureTime() {
        return departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.DEPARTURE_TIME
     *
     * @param departureTime the value for T_GW_ACCOUNT.DEPARTURE_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.CREATOR
     *
     * @return the value of T_GW_ACCOUNT.CREATOR
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.CREATOR
     *
     * @param creator the value for T_GW_ACCOUNT.CREATOR
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.CREATE_DTTM
     *
     * @return the value of T_GW_ACCOUNT.CREATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getCreateDttm() {
        return createDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.CREATE_DTTM
     *
     * @param createDttm the value for T_GW_ACCOUNT.CREATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setCreateDttm(Date createDttm) {
        this.createDttm = createDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.UPDATER
     *
     * @return the value of T_GW_ACCOUNT.UPDATER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.UPDATER
     *
     * @param updater the value for T_GW_ACCOUNT.UPDATER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.UPDATE_DTTM
     *
     * @return the value of T_GW_ACCOUNT.UPDATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getUpdateDttm() {
        return updateDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.UPDATE_DTTM
     *
     * @param updateDttm the value for T_GW_ACCOUNT.UPDATE_DTTM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setUpdateDttm(Date updateDttm) {
        this.updateDttm = updateDttm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_ENTRY_CONFIRM_NUM
     *
     * @return the value of T_GW_ACCOUNT.GW_ENTRY_CONFIRM_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Long getGwEntryConfirmNum() {
        return gwEntryConfirmNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_ENTRY_CONFIRM_NUM
     *
     * @param gwEntryConfirmNum the value for T_GW_ACCOUNT.GW_ENTRY_CONFIRM_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwEntryConfirmNum(Long gwEntryConfirmNum) {
        this.gwEntryConfirmNum = gwEntryConfirmNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_PAY_MONEY
     *
     * @return the value of T_GW_ACCOUNT.GW_PAY_MONEY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Long getGwPayMoney() {
        return gwPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_PAY_MONEY
     *
     * @param gwPayMoney the value for T_GW_ACCOUNT.GW_PAY_MONEY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwPayMoney(Long gwPayMoney) {
        this.gwPayMoney = gwPayMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GET_COLUMN_NUMBER
     *
     * @return the value of T_GW_ACCOUNT.GET_COLUMN_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Integer getGetColumnNumber() {
        return getColumnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GET_COLUMN_NUMBER
     *
     * @param getColumnNumber the value for T_GW_ACCOUNT.GET_COLUMN_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGetColumnNumber(Integer getColumnNumber) {
        this.getColumnNumber = getColumnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.JOB_DYNAMIC_INFORMATION_READTIME
     *
     * @return the value of T_GW_ACCOUNT.JOB_DYNAMIC_INFORMATION_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getJobDynamicInformationReadtime() {
        return jobDynamicInformationReadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.JOB_DYNAMIC_INFORMATION_READTIME
     *
     * @param jobDynamicInformationReadtime the value for T_GW_ACCOUNT.JOB_DYNAMIC_INFORMATION_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setJobDynamicInformationReadtime(Date jobDynamicInformationReadtime) {
        this.jobDynamicInformationReadtime = jobDynamicInformationReadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.CANDIDATE_DYNAMIC_READTIME
     *
     * @return the value of T_GW_ACCOUNT.CANDIDATE_DYNAMIC_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getCandidateDynamicReadtime() {
        return candidateDynamicReadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.CANDIDATE_DYNAMIC_READTIME
     *
     * @param candidateDynamicReadtime the value for T_GW_ACCOUNT.CANDIDATE_DYNAMIC_READTIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setCandidateDynamicReadtime(Date candidateDynamicReadtime) {
        this.candidateDynamicReadtime = candidateDynamicReadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.JOB_CONMUNICATE_TIME
     *
     * @return the value of T_GW_ACCOUNT.JOB_CONMUNICATE_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getJobConmunicateTime() {
        return jobConmunicateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.JOB_CONMUNICATE_TIME
     *
     * @param jobConmunicateTime the value for T_GW_ACCOUNT.JOB_CONMUNICATE_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setJobConmunicateTime(Date jobConmunicateTime) {
        this.jobConmunicateTime = jobConmunicateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.HUNT_NUM
     *
     * @return the value of T_GW_ACCOUNT.HUNT_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Integer getHuntNum() {
        return huntNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.HUNT_NUM
     *
     * @param huntNum the value for T_GW_ACCOUNT.HUNT_NUM
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setHuntNum(Integer huntNum) {
        this.huntNum = huntNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.POSITION_RANK
     *
     * @return the value of T_GW_ACCOUNT.POSITION_RANK
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Integer getPositionRank() {
        return positionRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.POSITION_RANK
     *
     * @param positionRank the value for T_GW_ACCOUNT.POSITION_RANK
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setPositionRank(Integer positionRank) {
        this.positionRank = positionRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_TYPE
     *
     * @return the value of T_GW_ACCOUNT.GW_TYPE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Integer getGwType() {
        return gwType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_TYPE
     *
     * @param gwType the value for T_GW_ACCOUNT.GW_TYPE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwType(Integer gwType) {
        this.gwType = gwType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_LEVEL
     *
     * @return the value of T_GW_ACCOUNT.GW_LEVEL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Integer getGwLevel() {
        return gwLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_LEVEL
     *
     * @param gwLevel the value for T_GW_ACCOUNT.GW_LEVEL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwLevel(Integer gwLevel) {
        this.gwLevel = gwLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.URL
     *
     * @return the value of T_GW_ACCOUNT.URL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.URL
     *
     * @param url the value for T_GW_ACCOUNT.URL
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_CITY
     *
     * @return the value of T_GW_ACCOUNT.GW_CITY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getGwCity() {
        return gwCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_CITY
     *
     * @param gwCity the value for T_GW_ACCOUNT.GW_CITY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwCity(String gwCity) {
        this.gwCity = gwCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.PREV_LOGIN_TIME
     *
     * @return the value of T_GW_ACCOUNT.PREV_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getPrevLoginTime() {
        return prevLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.PREV_LOGIN_TIME
     *
     * @param prevLoginTime the value for T_GW_ACCOUNT.PREV_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setPrevLoginTime(Date prevLoginTime) {
        this.prevLoginTime = prevLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.IS_INSIDE
     *
     * @return the value of T_GW_ACCOUNT.IS_INSIDE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getIsInside() {
        return isInside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.IS_INSIDE
     *
     * @param isInside the value for T_GW_ACCOUNT.IS_INSIDE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setIsInside(String isInside) {
        this.isInside = isInside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.ROLE_CODE
     *
     * @return the value of T_GW_ACCOUNT.ROLE_CODE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.ROLE_CODE
     *
     * @param roleCode the value for T_GW_ACCOUNT.ROLE_CODE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.NOW_LOGIN_TIME
     *
     * @return the value of T_GW_ACCOUNT.NOW_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Date getNowLoginTime() {
        return nowLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.NOW_LOGIN_TIME
     *
     * @param nowLoginTime the value for T_GW_ACCOUNT.NOW_LOGIN_TIME
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setNowLoginTime(Date nowLoginTime) {
        this.nowLoginTime = nowLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.RECOMMENF_QUALITY
     *
     * @return the value of T_GW_ACCOUNT.RECOMMENF_QUALITY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getRecommenfQuality() {
        return recommenfQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.RECOMMENF_QUALITY
     *
     * @param recommenfQuality the value for T_GW_ACCOUNT.RECOMMENF_QUALITY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setRecommenfQuality(String recommenfQuality) {
        this.recommenfQuality = recommenfQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.SERVE_QUALITY
     *
     * @return the value of T_GW_ACCOUNT.SERVE_QUALITY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getServeQuality() {
        return serveQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.SERVE_QUALITY
     *
     * @param serveQuality the value for T_GW_ACCOUNT.SERVE_QUALITY
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setServeQuality(String serveQuality) {
        this.serveQuality = serveQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_TELEPHONE
     *
     * @return the value of T_GW_ACCOUNT.GW_TELEPHONE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getGwTelephone() {
        return gwTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_TELEPHONE
     *
     * @param gwTelephone the value for T_GW_ACCOUNT.GW_TELEPHONE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwTelephone(String gwTelephone) {
        this.gwTelephone = gwTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.EXTENSION_NUMBER
     *
     * @return the value of T_GW_ACCOUNT.EXTENSION_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getExtensionNumber() {
        return extensionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.EXTENSION_NUMBER
     *
     * @param extensionNumber the value for T_GW_ACCOUNT.EXTENSION_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setExtensionNumber(String extensionNumber) {
        this.extensionNumber = extensionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.JOB_NUMBER
     *
     * @return the value of T_GW_ACCOUNT.JOB_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.JOB_NUMBER
     *
     * @param jobNumber the value for T_GW_ACCOUNT.JOB_NUMBER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_WECHAT
     *
     * @return the value of T_GW_ACCOUNT.GW_WECHAT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getGwWechat() {
        return gwWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_WECHAT
     *
     * @param gwWechat the value for T_GW_ACCOUNT.GW_WECHAT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwWechat(String gwWechat) {
        this.gwWechat = gwWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GW_QQ
     *
     * @return the value of T_GW_ACCOUNT.GW_QQ
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getGwQq() {
        return gwQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GW_QQ
     *
     * @param gwQq the value for T_GW_ACCOUNT.GW_QQ
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGwQq(String gwQq) {
        this.gwQq = gwQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.SELF_INTRODUCE
     *
     * @return the value of T_GW_ACCOUNT.SELF_INTRODUCE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public String getSelfIntroduce() {
        return selfIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.SELF_INTRODUCE
     *
     * @param selfIntroduce the value for T_GW_ACCOUNT.SELF_INTRODUCE
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setSelfIntroduce(String selfIntroduce) {
        this.selfIntroduce = selfIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_GW_ACCOUNT.GENDER
     *
     * @return the value of T_GW_ACCOUNT.GENDER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_GW_ACCOUNT.GENDER
     *
     * @param gender the value for T_GW_ACCOUNT.GENDER
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }
}