package com.springboot.xp.dao.mysql.mapper;

import com.springboot.xp.dao.mysql.model.GwAccount;
import com.springboot.xp.dao.mysql.model.GwAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GwAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    int countByExample(GwAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    int deleteByExample(GwAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    int insert(GwAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    int insertSelective(GwAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    List<GwAccount> selectByExample(GwAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    GwAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") GwAccount record, @Param("example") GwAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    int updateByExample(@Param("record") GwAccount record, @Param("example") GwAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    int updateByPrimaryKeySelective(GwAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_GW_ACCOUNT
     *
     * @mbggenerated Thu Jul 18 14:06:16 CST 2019
     */
    int updateByPrimaryKey(GwAccount record);
}